/**
 * Type-declaration generator for steem-js.
 *
 * The `steem.api` and `steem.broadcast` methods are generated at runtime from
 * `methods.js` / `operations.js`, so TypeScript can't infer them. This emits a complete
 * `dist/index.d.ts` from those same descriptors (plus hand-written interfaces for the
 * static modules), giving consumers full method-name autocomplete.
 *
 * Run via `npm run gen-types` (babel-node) — kept crypto-free so it loads without @noble.
 */
import fs from 'fs';
import path from 'path';
import methods from '../src/api/methods';
import operations from '../src/broadcast/operations';
import { camelCase } from '../src/utils';

const OUT = path.resolve(__dirname, '..', 'dist', 'index.d.ts');

const HELPERS = [
  ['addAccountAuth', '{ signingKey: string; username: string; authorizedUsername: string; role?: string; weight?: number }'],
  ['removeAccountAuth', '{ signingKey: string; username: string; authorizedUsername: string; role?: string }'],
  ['addKeyAuth', '{ signingKey: string; username: string; authorizedKey: string; role?: string; weight?: number }'],
  ['removeKeyAuth', '{ signingKey: string; username: string; authorizedKey: string; role?: string }'],
];

function apiBlock() {
  const lines = [];
  const seen = new Set();
  for (const m of methods) {
    const name = m.method_name || camelCase(m.method);
    if (seen.has(name)) continue;
    seen.add(name);
    const params = (m.params || []).map(p => `${safe(p)}: any`);
    const withCb = [...params, 'callback?: Callback'].join(', ');
    const withoutCb = params.join(', ');
    lines.push(`  /** RPC: \`${m.method}\` (${m.api}) */`);
    lines.push(`  ${name}(${withCb}): void;`);
    lines.push(`  ${name}Async(${withoutCb}): Promise<any>;`);
    lines.push(`  ${name}With(options: any, callback?: Callback): void;`);
    lines.push(`  ${name}WithAsync(options: any): Promise<any>;`);
  }
  return lines.join('\n');
}

function broadcastBlock() {
  const lines = [];
  const seen = new Set();
  for (const op of operations) {
    const name = camelCase(op.operation);
    if (seen.has(name)) continue;
    seen.add(name);
    const params = (op.params || []).map(p => `${safe(p)}: any`);
    const sig = ['wif: string', ...params, 'callback?: Callback'].join(', ');
    const roles = (op.roles || []).join(', ');
    lines.push(`  /** operation: \`${op.operation}\`${roles ? ` — roles: ${roles}` : ''} */`);
    lines.push(`  ${name}(${sig}): Promise<any>;`);
    lines.push(`  ${name}Async(${['wif: string', ...params].join(', ')}): Promise<any>;`);
  }
  for (const [name, opts] of HELPERS) {
    lines.push(`  ${name}(options: ${opts}, callback?: Callback): Promise<any>;`);
  }
  return lines.join('\n');
}

// keep identifiers valid (params are simple snake/camel names already)
function safe(p) { return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(p) ? p : `arg_${p}`; }

const out = `// Generated by scripts/gen-types.js from methods.js / operations.js — do not edit by hand.
// Regenerate with: npm run gen-types

export type Callback<T = any> = (error: any, result: T) => void;

export interface SteemOptions {
  url?: string;
  uri?: string;
  websocket?: string;
  transport?: 'http' | 'ws' | string;
  useAppbaseApi?: boolean;
  useTestNet?: boolean;
  address_prefix?: string;
  chain_id?: string;
  fetchMethod?: (uri: string, options: any) => Promise<any>;
  retry?: boolean | object;
  logger?: ((...args: any[]) => void) | { log: (...args: any[]) => void };
  [key: string]: any;
}

export type StreamMode = 'head' | 'irreversible';

export interface SteemApi {
${apiBlock()}

  // Raw JSON-RPC (HTTP transport only)
  call(method: string, params: any[], callback: Callback): void;
  callAsync(method: string, params: any[]): Promise<any>;
  signedCall(method: string, params: any[], account: string, key: string, callback: Callback): void;
  signedCallAsync(method: string, params: any[], account: string, key: string): Promise<any>;

  // Streaming (returns a release function to stop)
  streamBlockNumber(mode: StreamMode | Callback, callback?: Callback, ts?: number): () => void;
  streamBlock(mode: StreamMode | Callback, callback?: Callback): () => void;
  streamTransactions(mode: StreamMode | Callback, callback?: Callback): () => void;
  streamOperations(mode: StreamMode | Callback, callback?: Callback): () => void;

  // Lifecycle / config
  setOptions(options: SteemOptions): void;
  setWebSocket(url: string): void;
  setUri(url: string): void;
  start(): any;
  stop(): any;
  broadcastTransactionSynchronousWith(options: { trx: any }, callback?: Callback): any;

  /** Event emitter + dynamically generated members. */
  [key: string]: any;
}

export interface SteemBroadcast {
${broadcastBlock()}

  /** Sign and broadcast a raw transaction (supports multisig via an array of keys). */
  send(tx: any, privKeys: string[] | Record<string, string>, callback?: Callback): Promise<any>;
  sendAsync(tx: any, privKeys: string[] | Record<string, string>): Promise<any>;
  [key: string]: any;
}

export interface SteemAuth {
  verify(name: string, password: string, auths: any): boolean;
  generateKeys(name: string, password: string, roles: string[]): Record<string, string>;
  getPrivateKeys(name: string, password: string, roles?: string[]): Record<string, string>;
  isWif(privWif: string): boolean;
  toWif(name: string, password: string, role: string): string;
  wifIsValid(privWif: string, pubWif: string): boolean;
  wifToPublic(privWif: string): string;
  isPubkey(pubkey: string, addressPrefix?: string): boolean;
  signTransaction(trx: any, keys: string[]): any;
}

export interface SteemMemo {
  encode(privateKey: string, publicKey: string, memo: string, testNonce?: string): string;
  decode(privateKey: string, memo: string): string;
}

export interface SteemFormatter {
  reputation(reputation: number | string, decimalPlaces?: number): number;
  vestToSteem(vestingShares: number | string, totalVestingShares: number | string, totalVestingFundSteem: number | string): number;
  vestingSteem(account: any, gprops: any): number;
  amount(amount: number, asset: string): string;
  numberWithCommas(x: string): string;
  commentPermlink(parentAuthor: string, parentPermlink: string): string;
  estimateAccountValue(account: any, options?: any): Promise<string>;
  createSuggestedPassword(): string;
  pricePerSteem(feedPrice: { base: string; quote: string }): number | undefined;
}

export interface SteemUtils {
  validateAccountName(value: string): string | null;
  camelCase(str: string): string;
}

export interface SteemConfig {
  get(key: string): any;
  set(key: string, value: any): void;
  [key: string]: any;
}

export const api: SteemApi;
export const broadcast: SteemBroadcast;
export const auth: SteemAuth;
export const memo: SteemMemo;
export const formatter: SteemFormatter;
export const utils: SteemUtils;
export const config: SteemConfig;

declare const steem: {
  api: SteemApi;
  broadcast: SteemBroadcast;
  auth: SteemAuth;
  memo: SteemMemo;
  formatter: SteemFormatter;
  utils: SteemUtils;
  config: SteemConfig;
};

export default steem;
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out);
console.log(`Generated dist/index.d.ts — ${methods.length} api methods, ${operations.length} broadcast ops + ${HELPERS.length} helpers`);
